version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
  web:
    build: .
    command: python3 /opt/app/manage.py runserver 0.0.0.0:3001
    volumes:
      - .:/opt/app/
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db