# Generated by Django 2.0.4 on 2018-04-24 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def forward_update_message_ownership(apps, schema_editor):
    User = apps.get_model(
        app_label='auth',
        model_name='User')
    Message = apps.get_model(
        app_label='discordchat',
        model_name='Message')
    original_user = User.objects.get(username='powersjcb')

    Message.objects.all().update(user=original_user)


def reverse_update_message_ownership(apps, schema_editor):
    Message = apps.get_model('discordchat', 'Message')
    Message.objects.all().update(user=None)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discordchat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            forward_update_message_ownership,
            reverse_code=reverse_update_message_ownership,
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        )
    ]
