# Generated by Django 2.0.4 on 2018-04-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordchat', '0002_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='nonce',
            field=models.UUIDField(db_index=True, null=True, unique=True),
        ),
    ]
