# Generated by Django 2.0.4 on 2018-04-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordchat', '0003_message_nonce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='nonce',
            field=models.UUIDField(null=True),
        ),
    ]
