# Generated by Django 2.0.4 on 2018-05-02 00:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discordchat', '0005_channel_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='members',
            field=models.ManyToManyField(related_name='member_of', through='discordchat.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
