const SUBMIT_LOGIN = 'SUBMIT_LOGIN'
const SUBMIT_LOGOUT = 'SUBMIT_LOGOUT'
const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED'
const LOGIN_REFRESHED = 'LOGIN_REFRESHED'
const LOGIN_REFRESH_ACCESS = 'LOGIN_REFRESH_ACCESS'
const LOGIN_FAILED = 'LOGIN_FAILED'
const REQUEST_FAILED = 'REQUEST_FAILED'

export {
  SUBMIT_LOGIN,
  SUBMIT_LOGOUT,
  LOGIN_FAILED,
  LOGIN_SUCCEEDED,
  LOGIN_REFRESH_ACCESS,
  LOGIN_REFRESHED,
  REQUEST_FAILED,
}
