const SUBMIT_LOGIN = 'SUBMIT_LOGIN'
const SUBMIT_LOGOUT = 'SUBMIT_LOGOUT'
const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED'
const LOGIN_FAILED = 'LOGIN_FAILED'

export {
  SUBMIT_LOGIN,
  SUBMIT_LOGOUT,
  LOGIN_FAILED,
  LOGIN_SUCCEEDED,
}
